services:
  db:
    image: postgres:15
    container_name: system_monitoring_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data
  
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: system_monitoring-backend
    ports:
      - "8000:8000"
    env_file: .env
    environment: 
      - POSTGRES_HOST=db
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/app/docker-compose.yml
      - ./.env:/app/.env
    depends_on:
      - db

  frontend_react_vite:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: system_monitoring-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000


  nginx:
    image: nginx:alpine
    ports:
      - "8080-8090:80" # Range of ports so no conflicts

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: system_monitoring-agent
    command: ["python", "-m", "src.monitor"]
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  autoscaler:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: system_monitoring-autoscaler
    command: ["python", "-m", "src.autoscaler"]
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # Admin Badge to control Docker
      - ./docker-compose.yml:/app/docker-compose.yml  # The blueprint it knows what to scale
      - ./.env:/app/.env
    depends_on:
      - db

volumes:
  postgres_data_vol: