---
- name: System Monitoring App Infrastructure Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    # Linux Setup
    - name: Linux | Install Dependencies (Git, Python, Docker)
      when: ansible_facts['os_family'] == "Debian"
      become: true
      apt:
        name:
          - git
          - python3
          - python3-pip
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: yes
    - name: Linux | Ensure Docker service is running
      when: ansible_facts['os_family'] == "Debian"
      become: true
      service:
        name: docker
        state: started
        enabled: yes
    
    # macOS Setuo
    - name: macOS | Install Dependencies
      when: ansible_facts['os_family'] == "Darwin"
      homebrew:
        name:
          - git
          - python
        state: present
    - name: macOS | Install Docker Desktop
      when: ansible_facts['os_family'] == "Darwin"
      homebrew_cask:
        name: docker
        state: present
        accept_external_apps: yes

    # Deployment
    - name: Ensure the App Directory exists
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/system-monitoring-deployment"
        state: directory
    - name: Clone the repo
      git:
        repo: 'https://github.com/ahmadjon-rajabov/system_monitoring_app.git'
        dest: "{{ ansible_facts['env']['HOME'] }}/system-monitoring-deployment"
        version: main
        force: yes
        accept_hostkey: yes
    - name: Bootstrap .env file from template
      copy:
        src: "{{ ansible_facts['env']['HOME'] }}/system-monitoring-deployment/.env.example"
        dest: "{{ ansible_facts['env']['HOME'] }}/system-monitoring-deployment/.env"
        remote_src: yes
        force: no
    - name: Provide .env Template Instructions
      debug:
        msg: "IMPORTANT: Please ensure to update the .env file with GEMINI_API_KEY in {{ ansible_facts['env']['HOME'] }}/system-monitoring-deployment before launching"
    - name: Launch Docker sandbox
      shell: |
        cd "{{ ansible_facts['env']['HOME'] }}/system-monitoring-deployment"
        docker compose up -d --build
      ignore_errors: yes
      register: docker_output
    - name: Show Launch Status
      debug:
        msg: "Deployment Command Executed! Log: {{ docker_output.stderr | default(docker_output.stdout) }}"