name: System Monitoring App CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:  # Robot
  contents: read
  packages: write   # To upload Docker images to GitHub account

jobs:
  test-and-lint:
    name: Run Tests and Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reporistory
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync
      - name: Run Linter (Ruff)
        run: uv run ruff check .
      - name: Run Unit Tests with Coverage
        run: uv run pytest tests/ --cov=src --cov-fail-under=80

  build-and-publish:
    name: Build & Push Docker Images
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase Repository Name   # Docker requires lowercase names
        id: repo_name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Buidl and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ghcr.io/${{ env.REPO }}-backend:latest
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ghcr.io/${{ env.REPO }}-frontend:latest
